[workspace]
members = [
    # Scarb dependent crates.
    "crates/algebra",
    "crates/defi",
    "crates/map",
    "crates/random",
    "crates/rating",
    "crates/security",

    # Sozo dependent crates.
    "crates/token",
#    "governance"
]

[workspace.dependencies]
cubit = { git = "https://github.com/dojoengine/cubit", branch = "cairo_2.7" }
dojo = { git = "https://github.com/dojoengine/dojo", rev = "a35ddcb" }
starknet = "2.7.0-rc.3"

# Scripts are not supported for virtual workspaces.
