[package]
name = "origami_governance"
version = "1.0.0-alpha.0"
description = "Implementations of Compound Governance standards for the Dojo framework."
homepage = "https://github.com/dojoengine/origami/tree/governance"

[dependencies]
dojo.workspace = true

[tool.fmt]
sort-module-level-items = true

[lib]

[tool.dojo.world]
namespace = { default = "origami_governance" }
